"""Initial schema: all ten M1 entities.

Revision ID: 0001
Revises: None
Create Date: 2026-07-02

Hand-authored rather than autogenerated (see docs/schema_decisions.md
for why), so every statement below is the reviewable artifact the
Master Plan's "autogenerate-reviewed-by-hand" philosophy is actually
after. Mirrors src/infra/db/models/ exactly.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "zones",
        sa.Column("zone_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column(
            "oisd_area_classification",
            sa.String,
            nullable=False,
            server_default="unclassified",
        ),
        sa.Column("plant_section", sa.String, nullable=False),
        sa.Column("elevated_floor_override", sa.Numeric, nullable=True),
        sa.CheckConstraint(
            "oisd_area_classification IN ('zone_0', 'zone_1', 'zone_2', 'unclassified')",
            name="ck_zones_oisd_area_classification",
        ),
    )

    op.create_table(
        "workers",
        sa.Column("worker_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("role", sa.String, nullable=False),
        sa.Column(
            "current_zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("last_position_update", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('operator', 'supervisor', 'safety_officer', 'contractor', 'auditor')",
            name="ck_workers_role",
        ),
    )

    op.create_table(
        "zone_adjacency",
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "adjacent_zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.CheckConstraint("zone_id <> adjacent_zone_id", name="ck_zone_adjacency_not_self"),
    )

    op.create_table(
        "sensors",
        sa.Column("sensor_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("gas_type", sa.String, nullable=False),
        sa.Column("last_calibrated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alarm_threshold", sa.Numeric, nullable=False),
        sa.CheckConstraint(
            "gas_type IN ('CO', 'H2S', 'CH4', 'O2', 'COG_pressure', 'BFG_pressure')",
            name="ck_sensors_gas_type",
        ),
    )

    op.create_table(
        "equipment",
        sa.Column("equipment_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("equipment_type", sa.String, nullable=False),
        sa.Column("isolation_status", sa.String, nullable=False),
        sa.Column("maintenance_flag", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("loto_confirmed", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.CheckConstraint(
            "isolation_status IN ('isolated', 'active', 'degraded')",
            name="ck_equipment_isolation_status",
        ),
    )

    op.create_table(
        "permits",
        sa.Column("permit_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("permit_type", sa.String, nullable=False),
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "authorizing_officer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workers.worker_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("baseline_snapshot", postgresql.JSONB, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="active"),
        sa.CheckConstraint(
            "permit_type IN ('hot_work', 'confined_space', 'electrical_isolation', 'line_break')",
            name="ck_permits_permit_type",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'flagged', 'suspend_recommended', 'closed')",
            name="ck_permits_status",
        ),
    )
    op.create_index("ix_permits_zone_status", "permits", ["zone_id", "status"])
    op.create_index("ix_permits_status_expires", "permits", ["status", "expires_at"])

    op.create_table(
        "incidents",
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column(
            "linked_zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("date", sa.Date, nullable=False),
        sa.CheckConstraint(
            "source IN ('internal_near_miss', 'historical_case', 'regulatory_bulletin')",
            name="ck_incidents_source",
        ),
    )

    # sensor_readings and risk_assessments are created as plain tables
    # first, then converted with create_hypertable() below - Timescale
    # requires the table to already exist before that call.
    op.create_table(
        "sensor_readings",
        sa.Column("reading_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "sensor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sensors.sensor_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("gas_type", sa.String, nullable=False),
        sa.Column("value", sa.Numeric, nullable=False),
        sa.Column("unit", sa.String, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), primary_key=True, nullable=False),
        sa.Column("quality_flag", sa.String, nullable=False, server_default="ok"),
        sa.CheckConstraint(
            "gas_type IN ('CO', 'H2S', 'CH4', 'O2', 'COG_pressure', 'BFG_pressure')",
            name="ck_sensor_readings_gas_type",
        ),
        sa.CheckConstraint(
            "quality_flag IN ('ok', 'stale', 'out_of_calibration')",
            name="ck_sensor_readings_quality_flag",
        ),
    )
    op.execute(
        "SELECT create_hypertable('sensor_readings', 'timestamp', "
        "chunk_time_interval => INTERVAL '1 day')"
    )
    # DESC indexes need raw SQL - SQLAlchemy's declarative Index()
    # can't express column direction without a live column expression.
    op.execute(
        "CREATE INDEX ix_sensor_readings_zone_timestamp "
        "ON sensor_readings (zone_id, timestamp DESC)"
    )
    op.execute(
        "CREATE INDEX ix_sensor_readings_sensor_timestamp "
        "ON sensor_readings (sensor_id, timestamp DESC)"
    )

    op.create_table(
        "risk_assessments",
        sa.Column("assessment_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), primary_key=True, nullable=False),
        sa.Column("compound_risk_score", sa.Numeric, nullable=False),
        sa.Column("confidence", sa.Numeric, nullable=False),
        sa.Column("tier", sa.String, nullable=False),
        sa.Column("justification", postgresql.JSONB, nullable=False),
        sa.CheckConstraint(
            "tier IN ('watch', 'elevated', 'critical')", name="ck_risk_assessments_tier"
        ),
    )
    op.execute(
        "SELECT create_hypertable('risk_assessments', 'timestamp', "
        "chunk_time_interval => INTERVAL '1 day')"
    )

    op.create_table(
        "audit_log",
        sa.Column("log_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("event_type", sa.String, nullable=False),
        sa.Column("actor", sa.Text, nullable=False),
        sa.Column(
            "zone_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("zones.zone_id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint(
            "event_type IN ('risk_computed', 'permit_flagged', 'alert_sent', 'action_confirmed')",
            name="ck_audit_log_event_type",
        ),
    )


def downgrade() -> None:
    op.drop_table("audit_log")
    op.drop_table("risk_assessments")
    op.drop_table("sensor_readings")
    op.drop_table("incidents")
    op.drop_index("ix_permits_status_expires", table_name="permits")
    op.drop_index("ix_permits_zone_status", table_name="permits")
    op.drop_table("permits")
    op.drop_table("equipment")
    op.drop_table("sensors")
    op.drop_table("zone_adjacency")
    op.drop_table("workers")
    op.drop_table("zones")
