"""M27 Part 1 (Compliance & Standards Layer) - supporting regulatory/
industry-standard references for a recommendation the deterministic
engine already produced.

This package computes nothing and generates no recommendation. It is
a static, curated reference table keyed by the same recommendation
ids `src/knowledge_graph/recommendation_text.py` already defines
(`tier_critical`/`tier_elevated`/`tier_watch`, plus the 9 real rule
ids). Given a recommendation id, `standards_for_recommendation()`
returns the real published standards (or an honestly-labeled internal
Company SOP placeholder) that a safety engineer would cite as
supporting context for that recommendation - never the reason it was
generated. Display copy anywhere in this app must read "aligns with",
never "generated by".
"""
