import type { Recommendation } from "../../lib/recommendations";
import { standardsForRecommendation } from "../../lib/complianceStandards";

/**
 * M27 Part 1 (Compliance & Standards Layer) - each recommendation
 * already comes from the deterministic engine (tier + rules_fired);
 * the disclosure below only adds supporting regulatory/industry
 * references for it. It never explains why the recommendation exists
 * - that remains the engine's own justification, shown elsewhere. The
 * copy deliberately reads "aligns with", never "generated by".
 */
export function RecommendationList({ recommendations }: { recommendations: Recommendation[] }) {
  if (recommendations.length === 0) {
    return <p>No recommended actions for this assessment.</p>;
  }
  return (
    <ul className="recommendation-list">
      {recommendations.map((recommendation) => {
        const standards = standardsForRecommendation(recommendation.id);
        return (
          <li
            key={recommendation.id}
            className={`recommendation recommendation-${recommendation.severity}`}
          >
            <p className="recommendation-text">{recommendation.text}</p>
            {standards.length > 0 && (
              <details className="recommendation-standards">
                <summary>Supporting standards ({standards.length})</summary>
                <ul className="recommendation-standards-list">
                  {standards.map((standard) => (
                    <li key={standard.code + standard.title}>
                      <p className="recommendation-standard-heading">
                        Recommendation aligns with <strong>{standard.code}</strong> -{" "}
                        {standard.title}
                      </p>
                      <p className="recommendation-standard-summary">{standard.summary}</p>
                      <p className="recommendation-standard-applicability">
                        {standard.applicability}
                      </p>
                      <p className="recommendation-standard-reference">
                        {standard.externalReference}
                      </p>
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </li>
        );
      })}
    </ul>
  );
}
