/**
 * M27 Part 1 (Compliance & Standards Layer) - a verbatim mirror of
 * `src/compliance/standards.py`'s `STANDARDS_FOR_RECOMMENDATION` table,
 * the same cross-language constant-mirror pattern this codebase
 * already uses for recommendations/tiers/rule ids. These standards
 * support a recommendation the deterministic engine already produced;
 * they never generate one. Display copy must always read "aligns
 * with", never "generated by".
 */

export interface StandardReference {
  code: string;
  title: string;
  summary: string;
  applicability: string;
  externalReference: string;
}

function companySop(topic: string, summary: string): StandardReference {
  return {
    code: "Company SOP",
    title: `Company SOP - ${topic}`,
    summary,
    applicability: "Internal to this facility.",
    externalReference: "Internal document control system (not modeled in this demo).",
  };
}

const OSHA_GENERAL_DUTY: StandardReference = {
  code: "OSHA General Duty Clause",
  title: "Occupational Safety and Health Act, Section 5(a)(1)",
  summary:
    "Requires employers to furnish a workplace free from recognized hazards likely to cause death or serious physical harm.",
  applicability: "Applies whenever a zone's risk tier indicates a recognized, uncontrolled hazard.",
  externalReference: "29 U.S.C. §654(a)(1)",
};

const OSHA_CONFINED_SPACE: StandardReference = {
  code: "OSHA 1910.146",
  title: "Permit-Required Confined Spaces",
  summary:
    "Governs entry authorization, attendant duties, and headcount verification for permit-required confined spaces.",
  applicability:
    "Applies when personnel presence or permit status in a confined-space zone is in question.",
  externalReference: "29 CFR 1910.146",
};

const OSHA_LOTO: StandardReference = {
  code: "OSHA 1910.147",
  title: "The Control of Hazardous Energy (Lockout/Tagout)",
  summary: "Governs isolation of hazardous energy sources during servicing and maintenance.",
  applicability: "Applies when a permit status change affects equipment isolation.",
  externalReference: "29 CFR 1910.147",
};

const OSHA_PSM: StandardReference = {
  code: "OSHA 1910.119",
  title: "Process Safety Management of Highly Hazardous Chemicals",
  summary:
    "Requires management-of-change review and documented authorization for process modifications.",
  applicability: "Applies when a permit or work-authorization escalation affects a covered process.",
  externalReference: "29 CFR 1910.119",
};

const IEC_61511: StandardReference = {
  code: "IEC 61511",
  title: "Functional Safety - Safety Instrumented Systems for the Process Industry Sector",
  summary:
    "Defines fail-safe behavior, common-cause-failure considerations, and diagnostic/proof-testing requirements for safety instrumented systems.",
  applicability:
    "Applies whenever sensor or agent data is missing, stale, or a common-cause failure is suspected.",
  externalReference: "IEC 61511-1:2016",
};

const API_RP_754: StandardReference = {
  code: "API RP 754",
  title: "Process Safety Performance Indicators for the Refining and Petrochemical Industries",
  summary:
    "Defines Tier 1-4 process safety event indicators and leading indicators for escalating operational risk.",
  applicability: "Applies to tier escalations and simultaneous-operations (SIMOPS) risk compounding.",
  externalReference: "API Recommended Practice 754, 2nd Edition",
};

const NFPA_326: StandardReference = {
  code: "NFPA 326",
  title: "Standard for the Safeguarding of Tanks and Containers for Entry, Cleaning, or Repair",
  summary: "Governs atmospheric monitoring and safeguards for tank/container entry work.",
  applicability: "Applies to gas-monitoring zones with tank or vessel entry activity.",
  externalReference: "NFPA 326",
};

/** Mirrors `STANDARDS_FOR_RECOMMENDATION` in `src/compliance/standards.py` field-for-field. */
export const STANDARDS_FOR_RECOMMENDATION: Record<string, StandardReference[]> = {
  tier_critical: [
    OSHA_GENERAL_DUTY,
    API_RP_754,
    companySop("Emergency Response", "Evacuation and notification procedure for a critical-tier zone."),
  ],
  tier_elevated: [
    API_RP_754,
    companySop("Enhanced Monitoring", "Increased observation cadence for an elevated-tier zone."),
  ],
  tier_watch: [companySop("Routine Observation", "Standing watch-tier logging and review cadence.")],
  unauthorized_presence: [
    OSHA_CONFINED_SPACE,
    companySop("Access Control", "Headcount verification and unauthorized-entry response."),
  ],
  permit_status_escalated: [
    OSHA_LOTO,
    OSHA_PSM,
    companySop("Permit to Work", "Permit review and suspension/revocation procedure."),
  ],
  common_cause_grouped_degradation_count: [
    IEC_61511,
    API_RP_754,
    companySop("Equipment Reliability", "Inspection procedure for common-cause equipment degradation."),
  ],
  stale_data_fail_safe: [
    IEC_61511,
    companySop("Instrumentation Maintenance", "Technician dispatch procedure for stale sensor data."),
  ],
  missing_data_fail_safe: [
    IEC_61511,
    companySop("Instrumentation Maintenance", "Instrumentation-failure response procedure."),
  ],
  missing_location_fail_safe: [
    OSHA_CONFINED_SPACE,
    companySop("Personnel Tracking", "Manual headcount confirmation procedure."),
  ],
  missing_equipment_context: [
    NFPA_326,
    companySop("Equipment Status Verification", "Manual equipment status confirmation procedure."),
  ],
  agent_unavailable_using_last_known: [
    IEC_61511,
    companySop("System Health Monitoring", "Upstream system availability confirmation procedure."),
  ],
  interaction_bonus_applied: [
    API_RP_754,
    companySop("Simultaneous Operations (SIMOPS) Management", "Concurrent-activity review procedure."),
  ],
};

/** Supporting references for one recommendation id - never a reason it was generated. */
export function standardsForRecommendation(recommendationId: string): StandardReference[] {
  return STANDARDS_FOR_RECOMMENDATION[recommendationId] ?? [];
}
