import type { RiskAssessment } from "../api/types";
import { agentDisplayName, type RiskJustification } from "./justification";
import type { Recommendation } from "./recommendations";

/**
 * Item 7 (Executive Explanation) - a short natural-language summary
 * assembled entirely from already-persisted `justification` fields
 * and the already-deterministic `deriveRecommendations` output
 * (lib/recommendations.ts). This is a template, not a model: the same
 * assessment/justification/recommendations always produce the exact
 * same string, and every clause names a real value this tick's
 * `RiskAssessment` row already carries (agent names, raw risk,
 * interaction bonus multiplier, tier transition, top recommendation
 * text) - nothing here is generated by an LLM or inferred beyond what
 * the frozen engine already decided.
 */
export function generateExecutiveExplanation(
  assessment: RiskAssessment,
  justification: RiskJustification | null,
  recommendations: Recommendation[],
): string {
  if (!justification) {
    return `Assessment recorded at ${assessment.tier.toUpperCase()} (${assessment.compound_risk_score.toFixed(1)}); no structured justification is available for this tick.`;
  }

  const sortedAgents = Object.entries(justification.agentContributions).sort(
    (a, b) => b[1].risk - a[1].risk,
  );
  const [topAgentName, topAgent] = sortedAgents[0] ?? [undefined, undefined];
  const [secondAgentName, secondAgent] = sortedAgents[1] ?? [undefined, undefined];

  const sentences: string[] = [];

  if (topAgentName && topAgent) {
    let sentence = `${agentDisplayName(topAgentName)} contributed the highest raw risk this tick (${topAgent.risk.toFixed(1)})`;
    if (secondAgentName && secondAgent && secondAgent.risk >= 20) {
      sentence += `, with ${agentDisplayName(secondAgentName)} also elevated (${secondAgent.risk.toFixed(1)})`;
    }
    sentences.push(`${sentence}.`);
  }

  const interactionBonusApplied = justification.rulesFired.includes("interaction_bonus_applied");
  if (interactionBonusApplied) {
    sentences.push(
      `An interaction bonus (×${justification.interactionBonusApplied.toFixed(2)}) compounded these ` +
        `factors together, raising the compound score to ${assessment.compound_risk_score.toFixed(1)}.`,
    );
  }

  if (justification.tierBefore !== justification.tierAfter) {
    sentences.push(
      `Tier moved from ${justification.tierBefore.toUpperCase()} to ${justification.tierAfter.toUpperCase()}.`,
    );
  } else {
    sentences.push(`Tier held at ${justification.tierAfter.toUpperCase()}.`);
  }

  if (recommendations.length > 0) {
    sentences.push(`Recommended action: ${recommendations[0].text}`);
  }

  return sentences.join(" ");
}
