import type { RiskAssessment } from "../api/types";
import { agentDisplayName, type RiskJustification } from "./justification";
import type { Recommendation } from "./recommendations";

/**
 * Item 7 (Executive Explanation) - a short natural-language summary
 * assembled entirely from already-persisted `justification` fields
 * and the already-deterministic `deriveRecommendations` output
 * (lib/recommendations.ts). This is a template, not a model: the same
 * assessment/justification/recommendations always produce the exact
 * same string, and every clause names a real value this tick's
 * `RiskAssessment` row already carries (agent names, raw risk,
 * interaction bonus multiplier, tier transition, top recommendation
 * text) - nothing here is generated by an LLM or inferred beyond what
 * the frozen engine already decided.
 */
export function generateExecutiveExplanation(
  assessment: RiskAssessment,
  justification: RiskJustification | null,
  recommendations: Recommendation[],
): string {
  if (!justification) {
    return `Assessment recorded at ${assessment.tier.toUpperCase()} (${assessment.compound_risk_score.toFixed(1)}); no structured justification is available for this tick.`;
  }

  const sortedAgents = Object.entries(justification.agentContributions).sort(
    (a, b) => b[1].risk - a[1].risk,
  );
  const [topAgentName, topAgent] = sortedAgents[0] ?? [undefined, undefined];
  const [secondAgentName, secondAgent] = sortedAgents[1] ?? [undefined, undefined];

  const sentences: string[] = [];

  if (topAgentName && topAgent) {
    let sentence = `${agentDisplayName(topAgentName)} contributed the highest raw risk this tick (${topAgent.risk.toFixed(1)})`;
    if (secondAgentName && secondAgent && secondAgent.risk >= 20) {
      sentence += `, with ${agentDisplayName(secondAgentName)} also elevated (${secondAgent.risk.toFixed(1)})`;
    }
    sentences.push(`${sentence}.`);
  }

  const interactionBonusApplied = justification.rulesFired.includes("interaction_bonus_applied");
  if (interactionBonusApplied) {
    sentences.push(
      `An interaction bonus (×${justification.interactionBonusApplied.toFixed(2)}) compounded these ` +
        `factors together, raising the compound score to ${assessment.compound_risk_score.toFixed(1)}.`,
    );
  }

  if (justification.tierBefore !== justification.tierAfter) {
    sentences.push(
      `Tier moved from ${justification.tierBefore.toUpperCase()} to ${justification.tierAfter.toUpperCase()}.`,
    );
  } else {
    sentences.push(`Tier held at ${justification.tierAfter.toUpperCase()}.`);
  }

  if (recommendations.length > 0) {
    sentences.push(`Recommended action: ${recommendations[0].text}`);
  }

  return sentences.join(" ");
}

/** Cosmetic name -> one-clause business phrase per agent, used only by
 * `businessStoryLine` below. Never used to decide anything - purely a
 * shorter rewording of the same agent name `agentDisplayName` already
 * exposes, for the one-line-per-tick "story" framing (M23 Part 6)
 * rather than the fuller technical narration above. */
const AGENT_STORY_PHRASE: Record<string, string> = {
  gas_risk: "Gas concentration increasing",
  worker_exposure: "Worker entered a hazardous area",
  equipment_status: "Equipment degradation detected",
  permit_intelligence: "Permit conflict detected",
};

/**
 * M23 Part 6 (Executive Story) - a single, short, business-friendly
 * clause for one tick, in the style `demo_script.md` uses ("Gas
 * concentration increasing.", "Shutdown recommended."). Every branch
 * below reads only the same persisted `tierBefore`/`tierAfter` and top
 * agent contribution `generateExecutiveExplanation` already reads -
 * this is a shorter rewording for a different display context, not a
 * second computation.
 */
export function businessStoryLine(assessment: RiskAssessment, justification: RiskJustification | null): string {
  if (!justification) {
    return `Assessment recorded at ${assessment.tier.toUpperCase()}.`;
  }

  if (justification.tierAfter === "critical" && justification.tierBefore !== "critical") {
    return "Shutdown recommended.";
  }
  if (justification.tierAfter === "elevated" && justification.tierBefore !== "elevated") {
    return "Escalating - increased monitoring required.";
  }

  const [topAgentName] = Object.entries(justification.agentContributions).sort(
    (a, b) => b[1].risk - a[1].risk,
  )[0] ?? [undefined];

  if (topAgentName && AGENT_STORY_PHRASE[topAgentName]) {
    return `${AGENT_STORY_PHRASE[topAgentName]}.`;
  }

  return `Tier holding at ${justification.tierAfter.toUpperCase()}.`;
}
